battery:
  mass: 0.00295
  scale: 1
  volume: 1.5241500956828691e-06
driver:
  mass: 0.0013
  scale: 1
  volume: 5.7976850759745853e-08
hand_weight:
  mass: 0.00248
  scale: 1
  volume: 3.897712853003613e-07
hip_motor:
  mass: 0.00141
  scale: 1
  volume: 4.6408873411505935e-07
l_arm:
  mass: 0.00031
  scale: 1
  volume: 4.5989518393680296e-07
l_leg:
  mass: 0.0033
  scale: 1
  volume: 2.50080670476385e-06
mcu:
  mass: 0.00359
  scale: 1
  volume: 4.582732950505339e-07
r_arm:
  mass: 0.00047
  scale: 1
  volume: 3.56724429281643e-07
r_leg:
  mass: 0.00317
  scale: 1
  volume: 2.631959473823758e-06
weight:
  mass: 0.00149
  scale: 1
  volume: 2.599999937415033e-07
